// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type PrivateTodo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

func (PrivateTodo) IsTodo() {}

type Project struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ProjectTodo struct {
	ID      string   `json:"id"`
	Text    string   `json:"text"`
	Done    bool     `json:"done"`
	User    *User    `json:"user"`
	Project *Project `json:"project"`
}

func (ProjectTodo) IsTodo() {}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
